main_app/__init__.py
import datetime

from flask import Flask, request, session, render_template
from flask_login import LoginManager
from flask_mail import Mail
from flask_migrate import Migrate
from flask_security import Security, SQLAlchemyUserDatastore
from flask_security.forms import LoginForm
from flask_sqlalchemy import SQLAlchemy

from main_app.core.utils.tools import Tools

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
security = Security()
mail = Mail()


def create_app():
    app = Flask(__name__)

    # configure it in order -> prod overrides prp overrides dev
    app.config.from_pyfile('./config/dev.cfg', silent=True)
    app.config.from_pyfile('./config/prp.cfg', silent=True)
    app.config.from_pyfile('./config/prod.cfg', silent=False)

    db.init_app(app)
    migrate.init_app(app, db)
    mail.init_app(app)

    # configure security
    from main_app.core.db_models import User, Role
    user_datastore = SQLAlchemyUserDatastore(db, User, Role)

    class ExtendentLoginForm(LoginForm):
        def validate(self):
            email = Tools.bleach_clean(request.form['email'])
            if not email:
                self.errors['error'] = ['Login Audit System Prevents You From Login! Please Contact Administrators!']
                return False

            is_success = super(ExtendentLoginForm, self).validate()

            client_ip = None
            client_route_list = request.access_route
            if client_route_list:
                client_ip = Tools.bleach_clean(client_route_list[0])

            try:
                login_message = str(self.errors)
                session['post_login_redirect_url'] = self.next.data

                from main_app.core.db_models import LoginHistory
                proxy_ip = Tools.bleach_clean(request.remote_addr)
                user_agent = Tools.bleach_clean(request.headers.get('User-Agent'))
                email = Tools.bleach_clean(request.form['email'])
                browser = Tools.bleach_clean(request.user_agent.browser)
                login_history = LoginHistory(email=email,
                                             is_success=is_success,
                                             login_at=datetime.datetime.utcnow(),
                                             client_ip=client_ip,
                                             proxy_ip=proxy_ip,
                                             browser=browser,
                                             user_agent=user_agent,
                                             login_message=login_message)
                db.session.add(login_history)
                db.session.commit()

            except:
                is_success = False
                self.errors['error'] = ['Login Audit System Prevents You From Login! Please Contact Administrators!']

            return is_success

    login_manager.init_app(app)
    security_ctx = security.init_app(app=app, datastore=user_datastore,
                                     login_form=ExtendentLoginForm)

    @security_ctx.context_processor
    def security_send_password_reset_notice_context_processor():
        if request.access_route[0]:
            user_ip = Tools.bleach_clean(request.access_route[0])
        else:
            user_ip = Tools.bleach_clean(request.remote_addr)

        user_agent_platform = request.user_agent.platform
        user_agent_version = request.user_agent.version
        user_agent_browser = request.user_agent.browser

        return dict(log_date=datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S'),
                    user_ip=user_ip,
                    user_agent_platform=user_agent_platform,
                    user_agent_version=user_agent_version,
                    user_agent_browser=user_agent_browser)

    @app.before_first_request
    def before_first_request():
        from main_app.core.seeds import Seeds
        Seeds.create_default_user_and_roles(user_datastore)

    def __page_unauthorize(e):
        return render_template('401.html'), 401

    def __page_not_found(e):
        return render_template('404.html'), 404

    app.register_error_handler(404, __page_not_found)
    app.register_error_handler(401, __page_unauthorize)

    load_blueprints(app)
    from main_app.core.db_models import User
    return app


def load_blueprints(app):
    from main_app.userland.controller import mod_userland
    from main_app.userland.controllers.home_controller import mod_userland as mod_home
    from main_app.userland.controllers.admin_controller import mod_userland as mod_admin
    app.register_blueprint(mod_userland)

main_app/userland/controller.py
from flask import Blueprint

mod_userland = Blueprint('userland', __name__)

main_app/userland/controllers/admin_controller.py
from flask import render_template
from flask_security import login_required, roles_accepted

from main_app.core.utils.core_utils import CoreUtils
from main_app.userland.controller import mod_userland


@mod_userland.route('/admin')
@login_required
@roles_accepted('root')
def admin_home():
    controller_data = CoreUtils.get_controller_data()
    return render_template('userland/admin_home.html',
                           controller_data=controller_data,
                           current_page='admin_home',
                           title="Admin Home")

main_app/userland/controllers/home_controller.py
from flask import render_template, request, current_app, jsonify
from flask_mail import Message

from main_app import mail
from main_app.core.app_models import BaseResponse
from main_app.core.utils.core_utils import CoreUtils
from main_app.core.utils.tools import Tools
from main_app.userland.controller import mod_userland


@mod_userland.route('/')
def home():
    controller_data = CoreUtils.get_controller_data()
    return render_template('userland/home.html',
                           controller_data=controller_data,
                           current_page='home',
                           title="Home")


@mod_userland.route('/send_mail', methods=['POST'])
def send_mail():
    try:
        response = BaseResponse()
        name = Tools.bleach_clean(request.form['name'].strip())
        email = Tools.bleach_clean(request.form['email'].strip())
        subject = Tools.bleach_clean(request.form['subject'].strip())
        message = Tools.bleach_clean(request.form['message'].strip())

        if not name:
            response.fail(message="Please enter your name!")
        elif not email:
            response.fail(message="Please enter your email!")
        elif not message:
            response.fail(message="Please enter any message!")
        else:
            message = f'From: {email} \n\nMessage:\n{message}'

            mail.send(Message(subject=subject,
                              sender=(name, email),
                              recipients=current_app.config['MAIL_DEFAULT_RECEIVER'].split(','),
                              body=message))
            print('successs')

    except Exception as e:
        response.fail()

    return jsonify(response.__dict__)

main_app/templates/401.html
{% extends "userland/layout.html" %}

{% block content %}

    <div id="main_content">
        <div style="width: 50%; margin: 0 auto; padding: 50px;">
            <h1>401</h1>
            <div>Unauthorized Access.</div>
        </div>
    </div>

{% endblock %}

main_app/templates/security/forgot_password.html
{% extends "userland/security_layout.html" %}
{% block title %} Forgot Password {% endblock %}
{% block content %}

    <link href="static/css/login_user.css" rel="stylesheet">

    <h1>Forgot Password</h1>

    <div class="container-login100">
        <div class="login-box">
            <a href="/login">
                <div class="login100-form-title" style="background-image: url(static/img/logo/mfm-logo.png);"
                     onclick="/login">
                </div>
            </a>

            <form onsubmit="btn_reset_password_click()" action="{{ url_for_security('forgot_password') }}"
                  method="POST" name="forgot_password_form" id="forgot_password_form"
                  class="smart-form client-form">
                {{ forgot_password_form.hidden_tag() }}
                <div class="user-box">
                    <input type="text" name="" required="" data-validate="Email is required: ex@ex.com">
                    <label>Email</label>
                </div>
                <div class="flex-m w-full p-b-33">
                    <div class="container-login100-form-btn m-l-40">
                        <div class="wrap-login100-form-btn">
                            <div class="btn-contain" style="padding-top: 19px;">
                                <div class="btn-shiny-contain">
                                    <div class="btn-shiny">
                                        <button id="btn_reset_password"
                                                style="border-radius: 0px;"
                                                class="btn btn-light"
                                                type="submit"
                                                data-sitekey="{{ forgot_password_form.recaptcha_site_key }}">
                                            Reset Password
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}
{% block customscript %}

    <script>
        function btn_reset_password_click() {
            $('#btn_reset_password').LoadingOverlay("show", {
                fade: [50, 1000]
            });
        }

        {% if forgot_password_form.errors %}
            let errors = '';
            {% for error in forgot_password_form.errors  %}
                errors += '<p>{{ forgot_password_form.errors[error][0] | replace('\'','') }}</p>';
            {% endfor %}
            if (errors !== '') {
                Swal('Error', errors, 'error');
            }

        {% elif forgot_password_form.email.data != None %}
            $('#btn_reset_password').LoadingOverlay("hide", {
                fade: [50, 1000]
            });
            Swal('Sucess', 'Instructions to reset your password have been sent to your email address', 'success');
        {% endif %}

    </script>

{% endblock %}

main_app/templates/security/login_user.html
{% extends "userland/security_layout.html" %}
{% block title %} Login {% endblock %}
{% block content %}

    <h1>Login</h1>

    <link href="static/css/login_user.css" rel="stylesheet">

    <div class="container-login100">
        <div class="login-box">
            <div class="login100-form-title" style="background-image: url(static/img/logo/mfm-logo.png);">
            </div>

            <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form" id="login-form"
                  class="login100-form validate-form" onsubmit="login(); return false;">
                {{ login_user_form.hidden_tag() }}
                <div class="user-box">
                    <input type="text" name="email" required="">
                    <label>Email</label>
                </div>
                <div class="user-box">
                    <input type="password" name="password"  required="" >
                    <label>Password</label>
                </div>
                <div class="flex-m w-full p-b-33">
                    <div class="contact100-form-checkbox" style="width: 70%;">
                        <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember">
                        <label class="label-checkbox100" for="ckb1">
                            <span class="txt1">Remember Me</span>
                        </label>
                    </div>

                    <div class="container-login100-form-btn m-l-40">
                        <div class="wrap-login100-form-btn">
                            <div class="btn-contain" style="padding-top: 19px;">
                                <div class="btn-shiny-contain">
                                    <div class="btn-shiny">
                                        <div class="g-recaptcha"
                                             data-sitekey="{{ login_user_form.recaptcha_site_key }}"
                                             data-theme="dark"
                                             data-size="invisible"
                                             data-callback="login"></div>
                                        <button id="btn_submit"
                                                style="border-radius: 0px;"
                                                class="btn btn-light"
                                                type="submit">
                                            LOGIN
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="flex-m p-b-33 w-full">
                    <a href="/reset"><span> Forgot Password ? </span> </a>
                </div>
            </form>
        </div>

        <script>
            function login() {
                $('#btn_submit').LoadingOverlay("show", {
                    fade: [50, 1000]
                });
                document.getElementById('login-form').submit();
            }
        </script>


    </div>



    {% if login_user_form.errors %}
        {% block customscript %}
            <script>
                let errors = '';
                {% for error in login_user_form.errors  %}
                    errors += '<p>{{ login_user_form.errors[error][0] | replace('\'','') }}</p>';
                {% endfor %}
                if (errors !== '') {
                    Swal('400', errors, 'error');
                }

                $('#btn_submit').LoadingOverlay("hide", {
                    fade: [50, 1000]
                });

            </script>
        {% endblock %}
    {% endif %}

{% endblock %}

main_app/templates/security/reset_password.html
{% extends "userland/security_layout.html" %}
{% block title %}
    Reset Password
{% endblock %}
{% block content %}
    <div class="container-login100">
        <div class="wrap-login100 p-l-50 p-r-50 p-t-50 p-b-25">
            <a href="/login">
                <div class="login100-form-header p-b-30">
                    <img style="width: 60%;margin-top: 6px;" src="/static/img/logo/mfm-logo.png">
                </div>
            </a>
            <div>
                <div class="well no-padding">
                    <form id="reset_password_form" action="{{ url_for_security('reset_password', token=reset_password_token) }}" method="POST" name="reset_password_form" onsubmit="form_submit(); return false;">
                        {{ reset_password_form.hidden_tag() }}

                        <div class="wrap-input100" data-validate="Password is required">
                            <span class="label-input100"> New Password </span>
                            <input class="input100" type="password" id="password" name="password"
                                   pattern="(?=.*[0-9]+.*)(?=.*[a-z]+.*)(?=.*[A-Z]+.*).{6,128}$"
                                   title="Password must contain at least one lowercase letter, one uppercase letter, one number and length must be between 6 and 128 characters."
                                   placeholder="*******" required>
                        </div>

                        <div class="wrap-input100" data-validate="Confirm Password is required">
                            <span class="label-input100"> Confirm Password </span>
                            <input class="input100" type="password" id="password_confirm" name="password_confirm" pattern="(?=.*[0-9]+.*)(?=.*[a-z]+.*)(?=.*[A-Z]+.*).{6,128}$" onchange="this.setCustomValidity(this.validity.patternMismatch ? 'Password must contain at least one lowercase letter, one uppercase letter, one number and length must be between 6 and 128 characters.' : '');" placeholder="*******" required>
                        </div>

                        <div class="flex-m w-full p-b-33">
                            <div class="container-login100-form-btn">
                                <div class="wrap-login100-form-btn">
                                    <div class="btn-contain">
                                        <div class="btn-shiny-contain">
                                            <div class="btn-shiny">
                                                <button class="login100-form-btn pull-right"
                                                        id="btn_reset_password">
                                                    Reset Password
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block customscript %}

    <script>

        function form_submit() {
            let password = document.getElementById('password').value;
            let password_confirm = document.getElementById('password_confirm').value;

            if (password.length < 6 || password_confirm.length < 6) {
                Swal('400', 'Password must be at least 6 characters', 'error');
                return false;
            } else if (document.getElementById('password').value !== document.getElementById('password_confirm').value) {
                Swal('400', 'Passwords do not match', 'error');
                return false;
            } else {
                document.getElementById('reset_password_form').submit();
                $('#btn_reset_password').LoadingOverlay("show", {
                    fade: [50, 1000]
                });
            }
        }


        {% if reset_password_form.errors %}
            let errors = '';
            {% for error in reset_password_form.errors  %}
                errors += '<p>{{ reset_password_form.errors[error][0] | replace('\'','') }}</p>';
            {% endfor %}
            if (errors !== '') {
                Swal('Error', errors, 'error');
            }

            $('#btn_reset_password').LoadingOverlay("hide", {
                fade: [50, 1000]
            });

        {% endif %}
    </script>



{% endblock %}

main_app/templates/userland/admin_home.html
{% extends "userland/admin_layout.html" %}

{% block content %}

    <div>


        <section class="content-header">
            <h1>
                Admin Dashboard
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a>/ <b>Dashboard</b></li>
            </ol>
        </section>

        <div id="main_content">

        </div>

    </div>

{% endblock %}

main_app/templates/userland/admin_layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ title }} | MFM</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link href="/static/img/logo/mfm-logo-home.png" rel="icon">

    <!-- Bootstrap 3.3.2 -->
    <link href="/static/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <!-- FontAwesome 4.3.0 -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <!-- Ionicons 2.0.0 -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css"/>
    <!-- Theme style -->
    <link href="/static/admin/css/AdminLTE.min.css" rel="stylesheet" type="text/css"/>
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="/static/admin/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css"/>
    <!-- iCheck -->
    <link href="/static/lib/iCheck/flat/blue.css" rel="stylesheet" type="text/css"/>
    <!-- Morris chart -->
    <link href="/static/lib/morris/morris.css" rel="stylesheet" type="text/css"/>
    <!-- Date Picker -->
    <link href="/static/lib/datepicker/datepicker3.css" rel="stylesheet" type="text/css"/>
    <!-- Daterange picker -->
    <link href="/static/lib/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css"/>
    <!-- bootstrap wysihtml5 - text editor -->
    <link href="/static/lib/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" rel="stylesheet" type="text/css"/>
    <link href="/static/css/style.css" rel="stylesheet">

    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body class="skin-blue">
<div class="wrapper">

    <header class="main-header">

        <a href="/admin" class="logo" style="height: 70px; background-color: #000000;">
            <img src="/static/img/logo/mfm-logo.png" style="height: 100%;"/>
        </a>
        <nav class="navbar navbar-static-top" role="navigation">
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav" id="user_info_header_dropdown">

                    <!-- User Account -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="hidden-xs"> <i class="fa fa-user"></i> {{ current_user.first_name }} {{ current_user.last_name }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="user-header">
                                <p>
                                    <i class="fa fa-envelope-o text-success"></i> {{ current_user.email }}
                                    <small>Administrator</small>
                                <div>
                                    <a href="/logout" class="btn btn-danger btn-flat"><i class="fa fa-sign-out"></i> Sign out</a>
                                </div>
                                </p>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <!-- menu -->
    <aside class="main-sidebar" style="top:10px;">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left info" style="padding: 5px 5px 5px 5px;">
                    <p>{{ current_user.first_name }} {{ current_user.last_name }}</p>
                    <a href="#"><i class="fa fa-envelope-o text-success"></i> {{ current_user.email }}</a>
                </div>
            </div>


            <ul class="sidebar-menu">
                <li class="header">MAIN NAVIGATION</li>
                <li><a href="/admin"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li><a href="/admin/products"><i class="fa fa-cubes"></i> Products</a></li>
                <li><a href="/admin/carousal"><i class="fa fa-sliders"></i> Carousal</a></li>
                <li><a href="/admin/settings"><i class="fa fa-gears"></i> Settings</a></li>

{#                <li class="treeview">#}
{#                    <a href="#">#}
{#                        <i class="fa fa-edit"></i> <span>Forms</span>#}
{#                        <i class="fa fa-angle-left pull-right"></i>#}
{#                    </a>#}
{#                    <ul class="treeview-menu">#}
{#                        <li><a href="#"><i class="fa fa-circle-o"></i> General Elements</a></li>#}
{#                        <li><a href="#"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>#}
{#                        <li><a href="#"><i class="fa fa-circle-o"></i> Editors</a></li>#}
{#                    </ul>#}
{#                </li>#}
{##}
{##}
{#                <li class="treeview">#}
{#                    <a href="#">#}
{#                        <i class="fa fa-share"></i> <span>Multilevel</span>#}
{#                        <i class="fa fa-angle-left pull-right"></i>#}
{#                    </a>#}
{#                    <ul class="treeview-menu">#}
{#                        <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>#}
{#                        <li>#}
{#                            <a href="#"><i class="fa fa-circle-o"></i> Level One <i class="fa fa-angle-left pull-right"></i></a>#}
{#                            <ul class="treeview-menu">#}
{#                                <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>#}
{#                                <li>#}
{#                                    <a href="#"><i class="fa fa-circle-o"></i> Level Two <i class="fa fa-angle-left pull-right"></i></a>#}
{#                                    <ul class="treeview-menu">#}
{#                                        <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>#}
{#                                        <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>#}
{#                                    </ul>#}
{#                                </li>#}
{#                            </ul>#}
{#                        </li>#}
{#                        <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>#}
{#                    </ul>#}
{#                </li>#}
{#                <li class="header">LABELS</li>#}
{#                <li><a href="#"><i class="fa fa-circle-o text-danger"></i> Important</a></li>#}
{#                <li><a href="#"><i class="fa fa-circle-o text-warning"></i> Warning</a></li>#}
{#                <li><a href="#"><i class="fa fa-circle-o text-info"></i> Information</a></li>#}
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

    <div class="content-wrapper">
        {% block content %} {% endblock %}
    </div>

    <footer class="main-footer">
        <strong>Copyright &copy; 2020.</strong> All rights reserved.
    </footer>
</div>

<!-- jQuery 2.1.3 -->
<script src="/static/lib/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.2 -->
<script src="http://code.jquery.com/ui/1.11.2/jquery-ui.min.js" type="text/javascript"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.2 JS -->
<script src="/static/lib/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<!-- Morris.js charts -->
<script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="/static/lib/morris/morris.min.js" type="text/javascript"></script>
<!-- Sparkline -->
<script src="/static/lib/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>

<!-- daterangepicker -->
<script src="/static/lib/daterangepicker/daterangepicker.js" type="text/javascript"></script>
<!-- datepicker -->
<script src="/static/lib/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="/static/lib/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" type="text/javascript"></script>
<!-- iCheck -->
<script src="/static/lib/iCheck/icheck.min.js" type="text/javascript"></script>

<script src="/static/lib/loadingoverlay/loadingoverlay.min.js"></script>
<script src="/static/lib/sweetalert/sweetalert2.min.js"></script>

<script src="/static/admin/js/app.min.js" type="text/javascript"></script>
<script src="/static/js/tools.js" type="text/javascript"></script>

<script>

    $(function () {
        ajax_setup_default();
    });

    function ajax_setup_default() {
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                show_loading('#user_info_header_dropdown');
            },
            error: function (request, status, error) {
                hide_loading('#user_info_header_dropdown');
            },
            complete: function (request, status, error) {
                hide_loading('#user_info_header_dropdown');
            },
        });
    }

</script>

{% block customscript %}{% endblock %}
</body>
</html>

main_app/templates/userland/home.html
{% extends "userland/layout.html" %}

{% block content %}

    <main id="main">

      <h1>Flask APP Template</h1>

    </main>


{% endblock %}

{% block customscript %}
    <script charset="utf-8" type="text/javascript">
        function send_mail() {

            $('#mail_send_success').hide();
            $('#mail_send_fail').hide();

            const name = $('#name').val().trim();
            const email = $('#email').val().trim();
            const subject = $('#subject').val().trim();
            const message = $('#message').val().trim();

            $.ajax({
                url: "{{ url_for('userland.send_mail') }}",
                type: 'POST',
                data: {name: name, email: email, subject: subject, message: message},
                success: function (response) {
                    if (response.is_success) {
                        $('#mail_send_success').fadeIn("slow");
                    } else {
                        Swal(response.message, '', 'error');
                        $('#mail_send_fail').fadeIn("slow");
                    }
                },
                beforeSend: function () {
                    $('#send_mail_btn').LoadingOverlay("show", {
                        fade: [50, 1000]
                    });
                },
                complete: function () {
                    $('#send_mail_btn').LoadingOverlay("hide", {
                        fade: [50, 1000]
                    });
                }

            })


        }
    </script>

{% endblock %}